### ISSUE TITLE
local variable 'transformer' referenced before assignment

### ISSUE THREAD

**Issue by shubham-singh-ss** [creme-ml/creme#123] opened 2019-06-19 10:44 UTC
Hi,

I'm facing this issue while implementing the code from "building a time series model". 

Error says "local variable 'transformer' referenced before assignment" .

Kindly look into it.

**Comment by MaxHalford** [comment] 2019-06-19 11:50
Hey,

I just found the problem and fixed it. I'll be adding some unit tests soon to make sure the bug doesn't happen again.

Thanks for opening the issue!

**Comment by shubham-singh-ss** [comment] 2019-06-19 12:04
I just ran the code again, i'm still facing this issue

![Screenshot from 2019-06-19 17-29-56](https://user-images.githubusercontent.com/26729181/59763969-61905f00-92b8-11e9-9278-a9453ae08b5a.png)
![Screenshot from 2019-06-19 17-30-10](https://user-images.githubusercontent.com/26729181/59763989-69e89a00-92b8-11e9-85ab-6d72a4c64704.png)

**Comment by manugarri** [comment] 2019-06-19 12:05
same here, im using creme='0.2.0'

**Comment by MaxHalford** [comment] 2019-06-19 12:23
Yes, the fix is only for the development version... I'll push a new release this evening.

**Comment by shubham-singh-ss** [comment] 2019-06-19 12:27
Thanks...and amazing work done on Creme :)

**Comment by manugarri** [comment] 2019-06-19 13:46
great, thanks so much @MaxHalford , looking forward to the release :)

**Comment by shubham-singh-ss** [comment] 2019-06-20 05:19
still facing the error, you didn't remove the bug? @MaxHalford

**Comment by MaxHalford** [comment] 2019-06-20 07:51
The fix is available in the development version, which you can install using `pip install git+https://github.com/creme-ml/creme --upgrade`. I haven't released a new version on PyPI yet.

**Comment by shubham-singh-ss** [comment] 2019-06-20 07:56
when i run this code, it worked

![Screenshot from 2019-06-20 13-23-35](https://user-images.githubusercontent.com/26729181/59831230-ffd70000-935e-11e9-87ce-931ad777a4ad.png)

**Comment by shubham-singh-ss** [comment] 2019-06-20 07:58
the difference is that i didn't use the references "ordinal_date" and "month"....

**Comment by MaxHalford** [comment] 2019-06-20 08:00
I know what you mean. With the new version it now works in both cases. Also, in the new version the tutorial notebooks are unit tested along with the rest of the code.

**Comment by MaxHalford** [comment] 2019-06-21 02:13
I'm closing this because the issue is fixed. I'm delaying the release until next week because there a few new things that are nearly finished, and I prefer to make one big release.

**Closed by MaxHalford** 2019-06-21 02:13 UTC
Labels: bug
